"use client";
import Image from "next/image";import { AnimatePresence,motion,useReducedMotion } from "framer-motion";import useNich from "./useNich";
import { useBirthdayEventActive } from "../../../hooks/useBirthdayEventActive";
import { PartyHat } from "../../birthday/BirthdayIcons";
type Props={open:boolean;onClick:()=>void;onDismiss:()=>void;tourMode?:boolean};
export default function NichButton({open,onClick,onDismiss,tourMode=false}:Props){const reduce=useReducedMotion();const birthdayActive=useBirthdayEventActive();const{reaction,reactionKey,isReacting}=useNich();return <div className="fixed bottom-[calc(82px+env(safe-area-inset-bottom))] right-3 z-[80] flex flex-col items-end gap-2 lg:bottom-6 lg:right-6" data-tour="nich-floating-control">
  <AnimatePresence>{isReacting&&!open&&!tourMode&&<motion.button key={reactionKey} type="button" onClick={onClick} initial={{opacity:0,y:8,scale:.96}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:4}} transition={{duration:reduce?0:.2}} className="max-w-[220px] rounded-[14px] border border-violet-400/20 bg-[var(--surface-2)] px-3 py-2 text-left shadow-[var(--shadow-sm)]"><span className="block text-[9px] font-black uppercase tracking-[.15em] text-[var(--purple)]">{reaction.eyebrow||"Nich"}</span><span className="mt-1 block text-xs font-bold text-[var(--foreground)]">{reaction.message}</span></motion.button>}</AnimatePresence>
  <div className="group relative flex items-center gap-2"><div className="pointer-events-none absolute bottom-full right-1 mb-2 hidden whitespace-nowrap rounded-lg border border-[var(--border)] bg-[var(--surface-2)] px-2.5 py-1.5 text-[10px] font-bold text-[var(--foreground)] shadow-[var(--shadow-sm)] group-hover:block lg:block lg:opacity-0 lg:transition lg:group-hover:opacity-100">Need help with a trade?</div>{!tourMode&&<button type="button" onClick={onDismiss} aria-label="Hide NICH" className="flex h-11 w-11 items-center justify-center rounded-full border border-[var(--border)] bg-[var(--surface-2)] text-sm font-black text-[var(--foreground-muted)] shadow-sm transition hover:text-[var(--rose)]">×</button>}<button type="button" data-tour="nich-button" onClick={onClick} aria-label={open?"Close NICH":"Ask NICH"} aria-expanded={open} disabled={tourMode} className="flex min-h-[52px] items-center gap-2 rounded-[18px] border border-violet-400/25 bg-[var(--surface-2)] px-2.5 py-2 shadow-[var(--shadow-md)] transition hover:-translate-y-0.5 disabled:cursor-default disabled:opacity-100"><span className="relative h-9 w-9 rounded-[12px] bg-[var(--surface-nich)] ring-1 ring-violet-400/20"><span className="absolute inset-0 overflow-hidden rounded-[12px]"><Image src="/nich/nich-face.png" alt="" fill sizes="36px" className="object-cover object-[40%_12%]"/></span>{birthdayActive && <PartyHat aria-hidden="true" className="birthday-nich-button-hat h-6 w-6"/>}</span><span className="hidden pr-2 text-left sm:block"><span className="block text-[9px] font-black uppercase tracking-[.14em] text-[var(--purple)]">NICH AI</span><span className="block text-xs font-black text-[var(--foreground)]">{open?"Close":"Ask NICH"}</span></span></button></div>
</div>}
