import Link from "next/link";
import { SectionHeader } from "../ui/CSBTUI";
const actions=[
{href:"/exchange",icon:"↔",eyebrow:"Smart Marketplace",title:"Open Trade Finder",description:"Find inventory-aware matches, build offers, negotiate, and continue accepted trades in Trade Rooms.",buttonLabel:"Enter Exchange",tone:"smart"},
{href:"/values",icon:"◇",eyebrow:"Values",title:"Check Values",description:"Search the full database and compare GCash and Elve values.",buttonLabel:"Browse Values",tone:"gold"},
{href:"/calculator",icon:"±",eyebrow:"Trade",title:"Compare a Trade",description:"Put both offers side by side and review the estimated value difference.",buttonLabel:"Open Calculator",tone:"neutral"},
{href:"/inventory",icon:"▣",eyebrow:"My CSBT",title:"Manage Inventory",description:"Save your items, quantities, and variants so CSBT can power personal trading tools.",buttonLabel:"Open Inventory",tone:"neutral"},
{href:"/demand",icon:"↗",eyebrow:"Market",title:"Check Demand",description:"Look beyond raw value and review market movement before deciding.",buttonLabel:"View Demand",tone:"smart"},
{href:"/trade-feed",icon:"◎",eyebrow:"Community",title:"Vote on Trades",description:"Browse real community trades and vote Win, Fair, or Lose.",buttonLabel:"View Trade Opinions",tone:"neutral"},
{href:"/nich",icon:"✦",eyebrow:"Nich AI",title:"Ask Nich",description:"Ask about values, trades, nearby items, and how to use CSBT HUB.",buttonLabel:"Ask Nich",tone:"nich"},] as const;
const toneClass={smart:"border-cyan-400/20 bg-cyan-500/[.035] text-[var(--cyan)]",gold:"border-[var(--border-gold)] bg-amber-500/[.035] text-[var(--gold-dark)]",nich:"border-violet-400/20 bg-violet-500/[.035] text-[var(--purple)]",neutral:"border-[var(--border)] bg-[var(--surface-2)] text-[var(--foreground-muted)]"} as const;
export default function QuickActions(){return <section><SectionHeader eyebrow="Explore CSBT HUB" title="Pick the tool for what you want to do" description="Trade, check values, manage inventory, follow the market, learn from the community, or ask Nich."/><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{actions.map(a=><Link key={a.href} href={a.href} className={`group csbt-card-hover flex min-h-[210px] flex-col rounded-[var(--radius-card)] border p-5 shadow-[var(--shadow-sm)] ${toneClass[a.tone]}`}><span className="flex h-11 w-11 items-center justify-center rounded-[13px] bg-[var(--surface-2)] text-lg font-black shadow-sm ring-1 ring-[var(--border)]" aria-hidden="true">{a.icon}</span><p className="mt-5 text-[9px] font-black uppercase tracking-[.16em] opacity-75">{a.eyebrow}</p><h3 className="mt-1.5 text-lg font-black tracking-[-.025em] text-[var(--foreground)]">{a.title}</h3><p className="mt-2 text-sm font-medium leading-6 text-[var(--foreground-muted)]">{a.description}</p><span className="mt-auto pt-5 text-xs font-black text-[var(--foreground)]">{a.buttonLabel} →</span></Link>)}</div></section>}
